### ISSUE TITLE
Karma segmentation faults & strange duplicate processes

### ISSUE THREAD

**Issue by JaKXz** [karma-runner/gulp-karma#14]
*disclaimer/note:* Below a snippet from my `gulpfile.js` that provides the relevant context for my issue. If it's found that I should move this question to S/O I will happily do so, but I'm wondering if anyone has seen some similar issues with gulp-karma.

I'm using karma with mocha and browserify to run tests against my Angular app on PhantomJS or Chrome. When I use the `singleRun: false` option (via `gulp test --watch [--debug]`), I see a lot of errors like this after some TDD cycles:

```
SUMMARY:
✔ 19 tests completed
Segmentation fault: 11
```

and then the task ends unexpectedly. Then when I go to just run the tests once through to see if they're all passing, I see:

```
SUMMARY:
✔ 38 tests completed
[14:17:37] Finished 'test' after 10 s
```

which shows a) an unexpectedly long time to run the test task, and b) a doubled number of tests. When I run `ps aux | grep node` after this I see two different karma processes and as a workaround for now I just `kill -9 <PID>` one of them, but, I'm wondering: **why am I seeing the segmentation faults?** These issues are blocking me from TDD. Any help is appreciated!

```javascript
...
var karma = require('karma').server;
var gutil = require('gulp-util');

gulp.task('test', function (done) {
  karma.start({
    configFile: __dirname + '/karma.conf.js',
    singleRun: !gutil.env.watch,
    browsers: gutil.env.debug ? ['Chrome'] : ['PhantomJS']
  }, done);
});
...
```

**Comment by pkozlowski-opensource** [comment]
@JaKXz I would be surprised if it is linked to this project (that is - gulp integration). Did you try to run karma directly from a command line and not from gulp? What happens in this case?

**Comment by JaKXz** [comment]
@pkozlowski-opensource looks like you've got a point... using `karma start` seems (at first and short glance) to be more stable.

**Comment by JaKXz** [comment]
@pkozlowski-opensource Actually, it looks like `karma start` is giving me the *both* of the same issues... any guesses to where the root of the problem is?

**Comment by pkozlowski-opensource** [comment]
I'm sorry, but I don't think anyone will be able to help without a clear reproduce scenario.... Closing, I hope you've managed to sort it out on your end...

**Comment by srdone** [comment]
I was seeing this issue with karma and occasionally with webpack. We were using babel-loader in the karma config. We updated our setup to use the packages recommended by babel for use in karma (`karma-babel-preprocessor`) and making sure webpack was using the latest version of `babel-loader` the issue has stopped. See babel's recommendations at http://babeljs.io/docs/setup/#karma
