### ISSUE TITLE
How can I pipe files to karma?

### ISSUE THREAD

**Issue by hyzhak** [karma-runner/gulp-karma#17]
I need to make some preprocessing on files and want after that to pipe them to Karma test runner. How can I archive it with gulp?

**Comment by pkozlowski-opensource** [comment]
You can't. What you should be doing is to [preprocessors](http://karma-runner.github.io/0.12/config/preprocessors.html) to transform files before those are served to a browser.

An alternative would be to watch spacify Gulp's output folder as input for Karma.
