### ISSUE TITLE
using karma watch and gulp watch together requires double CTRL-C

### ISSUE THREAD

**Issue by tardyp** [karma-runner/gulp-karma#26]
do my tdd setup, I use gulp watch to transpile coffeescripts and jade into a static repository, which is then watched by karma to run the unit test.

Problem is that when I first hit CTRL-C, then the gulp.watch does not detect it I need to hit a second time to end the process.

ugly workaround:
```
        mydone = ->
            done()
            # need process.exit to avoid need for a double ctrl-c
            # karma watch is overriding ctrl-c, then the gulp watch does not see it
            process.exit()
        server = new karma.Server(karmaconf, mydone)
        server.start()
```

**Comment by tardyp** [comment]
mmhh shall I rather file against karma-runner/karma ?

**Comment by pkozlowski-opensource** [comment]
> my tdd setup, I use gulp watch to transpile coffeescripts and jade into a static repository, which is then watched by karma to run the unit test.

This is not an ideal approach - why not using Karma plugin to do transpilation? This way you would avoid 2 watches. 

> mmhh shall I rather file against karma-runner/karma ?

Only if you are sure that Karma is to blame here...
