### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ilanbiala** [karma-runner/gulp-karma#27]
A changelog would be great to know what changes between versions.

**Comment by Dignifiedquire** [comment]
As this is not actually a library that you install, but rather a set of examples, what exactly would you be looking for in a changelog that is not covered by looking at the commit history?

**Comment by pkozlowski-opensource** [comment]
Agree with @Dignifiedquire - we don't have any releases so I don't see what a changelog could contain...

**Comment by ilanbiala** [comment]
Yeah sorry, I looked at it, couldn't find much info so I filed the issue, then looked back at the deprecation and forgot to close this.
