### ISSUE TITLE
Process exits with 1 minute delay

### ISSUE THREAD

**Issue by tsalzinger** [karma-runner/gulp-karma#5]
I currently use gulp-karma for executing my tests from within gulp but as I'm no fan of all the gulp wrappers around existing functionality I wanted to switch to the proposed method described here. The setup and configuration was pretty straight forward but somehow karma prevents the whole process from shutting down (It does so eventually - with 1 minute delay to be specific).

My issue can be seen by the following output (i added a small wrapper which prints timestamps before and after executing gulp):

```
Starting @ 10:36:03,69
[gulp] Using gulpfile C:\private\src\gulp-karma\gulpfile.js
[gulp] Starting 'test'...
INFO [karma]: Karma v0.12.16 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 35.0.1916 (Windows)]: Connected on socket tRl4URuNtzR0dDTX-NG8 with
Chrome 35.0.1916 (Windows): Executed 1 of 1 SUCCESS (0.01 secs / 0.001 secs)
[gulp] Finished 'test' after 2.38 s
Finished @ 10:37:06,52
```

After some research I discovered that this isn't a 'new' issue, but should be fixed in the latest release (0.12.16).
The issues i found:
https://github.com/karma-runner/gulp-karma/issues/3
https://github.com/karma-runner/karma/issues/1035
https://github.com/karma-runner/karma/issues/1054

**Comment by noelmace** [comment]
I still get this bug ... exit after 1 minute.

Yet, I'm on node 5.4.0 with gulp 3.9.0 and karma 0.13.19.

**Comment by nonplus** [comment]
+1

I work around the problem by explicitly specifying `karma 0.13.18` and `socket.io 1.3.7` in my `package.json` file.

**Comment by Dignifiedquire** [comment]
This is being tracked in https://github.com/karma-runner/karma/issues/1788

**Comment by Dignifiedquire** [comment]
@pkozlowski-opensource if you got a moment to look into this, as you were able to track this down the last time I'd appreciate it.

**Comment by shuyudev** [comment]
Still get this. There is huge delay for exit.
Karma 1.4.0
Gulp 4.0.0
Node 6.5.0

**Comment by johannesjo** [comment]
Still an issue..
