### ISSUE TITLE
Gulp exists with code 0 even if tests fail

### ISSUE THREAD

**Issue by pkozlowski-opensource** [karma-runner/gulp-karma#6]
With the current setup Gulp doesn't exit with non-zero error code when tests are failing in the `test` task - if Karma run is the only operation we should exit Gulp process with the Karma's exit code.

**Comment by JaKXz** [comment]
I'm running gulp `3.8.10+` and my CI server is getting an exit code of 0 from my `gulp test` task... Not really sure where to start?

**Comment by sabrinaluo** [comment]
~~I have the same issue~~

**Comment by sabrinaluo** [comment]
Hi, I think the problem is how you config karma in gulp.
Please notice that, `done` is a function which takes **1 argument**
`// function (err) {finish(err, 'callback');}`

:white_check_mark: :smile: 

```
gulp.task('test', function (done) {
  new Server({
    configFile: __dirname + '/../karma.conf.js',
    singleRun: true
  }, done).start();
});
```

:white_check_mark: :smile: 

```
gulp.task('test', function (done) {
  new Server({
    configFile: __dirname + '/../karma.conf.js',
    singleRun: true
  }, function(err){
    done(err);
  }).start();
});
```

:x: :x: :x: :cry: 

```
gulp.task('test', function (done) {
  new Server({
    configFile: __dirname + '/../karma.conf.js',
    singleRun: true
  }, function(){
    done();
  }).start();
});
```
